services:
  postgis:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    container_name: postgis-dev
    env_file:
      - ./apps/backend/.env.development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: nestjs-handler-error
      PGDATABASE: nestjs-handler-error
      PGDATA: /data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d nestjs-handler-error']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-handle-error-network

  redis:
    image: redis:8-alpine
    container_name: redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    env_file:
      - ./apps/backend/.env.development
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-handle-error-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
  emqx_data:
  emqx_log:
    # pgadmin:

networks:
  nestjs-handle-error-network:
    driver: bridge
